server:
  port: 8088
# 请求路径
neteaseMusic:
  baseUrl: "http://music.163.com/"
  banner: "api/v2/banner/get"
  personalizedPlayList: "weapi/personalized/playlist"
  discoveryNewAlbum: "api/discovery/newAlbum"
  playlistDetail: "weapi/v3/playlist/detail"
  topList: "weapi/v3/playlist/detail"
  songUrl: "weapi/song/enhance/player/url"
  lyric: "weapi/song/lyric"
  songDetail: "weapi/v3/song/detail"
  album: "weapi/v1/album"
  commentMusic: "weapi/v1/resource/comments/R_SO_4_"
  commentHot: "weapi/v1/resource/hotcomments"
  recommendSongs: "weapi/v2/discovery/recommend/songs"
  userPlayList: "weapi/user/playlist"
  search: "weapi/cloudsearch/get/web"
  loginCellphone: "weapi/login/cellphone"
  login: "weapi/login"
  recommendResource: "weapi/v1/discovery/recommend/resource"
  mvDetail: "weapi/mv/detail"
  videoDetail: "weapi/cloudvideo/v1/video/detail"
  mvUrl: "weapi/song/enhance/play/mv/url"
  videoUrl: "weapi/cloudvideo/playurl"
  relatedAllvideo: "weapi/cloudvideo/v1/allvideo/rcmd"
  commentMv: "weapi/v1/resource/comments/R_MV_5_"
  commentVideo: "weapi/v1/resource/comments/R_VI_62_"