server:
  port: 8088
# 请求路径
neteaseMusic:
  baseUrl: "http://music.163.com/"
  topList: "/weapi/v3/playlist/detail"
  songUrl: "/weapi/song/enhance/player/url"
#  lyric: "/weapi/song/media"
  lyric: "/weapi/song/lyric"