server:
  port: 8088
# 请求路径
neteaseMusic:
  baseUrl: "http://music.163.com/"
  topList: "weapi/v3/playlist/detail"
  songUrl: "weapi/song/enhance/player/url"
  lyric: "weapi/song/lyric"
  songDetail: "weapi/v3/song/detail"
  album: "weapi/v1/album"
  commentMusic: "weapi/v1/resource/comments/R_SO_4_"
  commentHot: "weapi/v1/resource/hotcomments"
  recommendSongs: "weapi/v2/discovery/recommend/songs"
  userPlayList: "weapi/user/playlist"